apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
  namespace: nodejs
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  sessionAffinity: None
